
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 21 18:17:55 CST 2013
//----------------------------------------------------

package smallc.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int SR = 30;
  public static final int AA = 20;
  public static final int GE = 31;
  public static final int SL = 29;
  public static final int PI = 45;
  public static final int DA = 23;
  public static final int PD = 46;
  public static final int MA = 22;
  public static final int SEMI = 10;
  public static final int CONTINUE = 4;
  public static final int INT = 53;
  public static final int SA = 21;
  public static final int FOR = 6;
  public static final int LT = 34;
  public static final int TYPE = 9;
  public static final int LP = 13;
  public static final int LO = 39;
  public static final int COMMA = 11;
  public static final int LN = 37;
  public static final int DIV = 48;
  public static final int RP = 14;
  public static final int IF = 2;
  public static final int UM = 44;
  public static final int ID = 52;
  public static final int DOT = 12;
  public static final int BAA = 24;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int LC = 17;
  public static final int LB = 15;
  public static final int RETURN = 7;
  public static final int LA = 38;
  public static final int BX = 43;
  public static final int error = 1;
  public static final int RC = 18;
  public static final int MUL = 47;
  public static final int RB = 16;
  public static final int ADD = 50;
  public static final int MOD = 49;
  public static final int BREAK = 5;
  public static final int BO = 42;
  public static final int EQ = 35;
  public static final int BN = 40;
  public static final int ELSE = 3;
  public static final int BA = 41;
  public static final int NE = 36;
  public static final int BOA = 26;
  public static final int SLA = 27;
  public static final int AS = 19;
  public static final int STRUCT = 8;
  public static final int SRA = 28;
  public static final int GT = 32;
  public static final int SUB = 51;
  public static final int BXA = 25;
}

